Added the missing exceptions of class Player
GameEndsException: throw when a player gets 10 (or more) points
OutOfRangeException: throw when a value is out of range